#!/bin/bash

if command -v paru &> /dev/null
then
    sudo pacman -Syu
    paru -S --noconfirm --needed base-devel opendoas hyprland waybar-hyprland swaybg rofi kitty
else
  echo "this only works with ArchLinux try to install it your self"
fi


echo "Installing hyprland"
echo "checking for ~/.config/hypr"
mv ~/.config/hypr ~/.config/hypr.bc
echo "copy the config to ~/.config/hypr"
cp -r ./config/hypr/ ~/.config/hypr/

echo "Installing rofi"
echo "checking for ~/.config/rofi"
mv ~/.config/rofi ~/.config/rofi.bc
echo "copy the config to ~/.config/rofi"
cp -r ./config/rofi/ ~/.config/rofi/
